backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - file: "content/settings/home.yml"
        label: "Homepage"
        name: "home"
        fields:
          - { label: "Hero Headline", name: "hero_headline", widget: "string" }
          - { label: "Hero Subtext", name: "hero_subtext", widget: "text" }
          - { label: "CTA Text", name: "cta_text", widget: "string", default: "Book a Consultation" }